{% set version = '0.11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-evaluate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/evaluate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/evaluate/evaluate_{{ version }}.tar.gz
  sha256: b04805ffb56d82e2d5b044aa32de7e9ef4162ea619fd368f83e03dbd49631bcd

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, lattice, ggplot2
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-stringr >=0.6.2

  run:
    - r-base
    - r-stringr >=0.6.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('evaluate')"           # [not win]
    - "\"%R%\" -e \"library('evaluate')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/evaluate
  license: MIT + file LICENSE
  summary: Parsing and evaluation tools that make it easy to recreate the command line behaviour
    of R.
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: evaluate
# Type: Package
# Title: Parsing and Evaluation Tools that Provide More Details than the Default
# Version: 0.11
# Authors@R: c( person("Hadley", "Wickham", role = "aut"), person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person("Michael", "Lawrence", role = "ctb"), person("Thomas", "Kluyver", role = "ctb"), person("Jeroen", "Ooms", role = "ctb"), person("Barret", "Schloerke", role = "ctb"), person("Adam", "Ryczkowski", role = "ctb"), person("Hiroaki", "Yutani", role = "ctb") )
# Description: Parsing and evaluation tools that make it easy to recreate the command line behaviour of R.
# License: MIT + file LICENSE
# URL: https://github.com/r-lib/evaluate
# BugReports: https://github.com/r-lib/evaluate/issues
# Depends: R (>= 3.0.2)
# Imports: methods, stringr (>= 0.6.2)
# Suggests: testthat, lattice, ggplot2
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-07-17 19:45:22 UTC; yihui
# Author: Hadley Wickham [aut], Yihui Xie [aut, cre] (<https://orcid.org/0000-0003-0645-5666>), Michael Lawrence [ctb], Thomas Kluyver [ctb], Jeroen Ooms [ctb], Barret Schloerke [ctb], Adam Ryczkowski [ctb], Hiroaki Yutani [ctb]
# Maintainer: Yihui Xie <xie@yihui.name>
# Repository: CRAN
# Date/Publication: 2018-07-17 20:10:02 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
