travis:
  secure:
    BINSTAR_TOKEN: QudbXbH/lkAD+CuCAiel69iXgSpsqkGOrsFoJPzfVK6CkUqHvX1VcEaWfZWiJ5uEcQri/VMj9Qmxx2fWogE65p3zICPrewmhcKurs/ES2nIOhhVDJrCNnE+czEx53K+F8suiPU+xuYfY05ne4n9Jlg9CYGtLMSmwsYflbFLjur1zQUgScSj78Ubz4sBCu1L0kFKwIhbgnhSgNtIDPzY8xYsZUAjEZkd1GPNOWK5KxV0+h5PIy29Jo7mOxX8KUbb/r1Agm76vEhYTykvxxLl8fXWElMB8AVvPcWIv2mLeHP2IM+nffxQp4B+iBfeSwninaSrwLrQObyxfblm/B9KfRkLQiFBvE1Sav75ZzUVrA8MWg//vY36B0qWqNK2nqQOqMAdwT9g1ZMCMLaGoqJAymevn5OF0PYU5ouBed0n+NgWTYjDtb9xbKMHgPmADCmGMbyKXKLCrI//kSmN/HejFnJRGjx12Vtr06A6f7qU+TydTwe/276KfQzNqqmSBWMBWN8CPTi+OV7SWY0Q1Ue/3AkdSu5QRRokmDeZgwowKj4eqS9E8A9F1YychpSXWGrClGSUkkXFZXDsDDrmKvJ6+R8GGbpXIEuQdqpVSiU7zZhYDe3XVmWWHcpBKFD6+evX13er7m9xX79kQ1/L88zn7frTR8WfX91kth3gGvNGrQAc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
