travis:
  secure:
    BINSTAR_TOKEN: AQG3OAeLTQLWpibFctSrV0/OM6+RxNwm46bT9jdFZYd9d1O7xYgeTMHCu7Jd15rs6Gl8qFaOM3/P5EkMfGhHLajt+2oUNxOza+GL4oOKUICak37etD+aEnF9X5MzmtNPmfvgyozcOupaVyC+SC5gIsLcyWTrbnYvqGJH8QdZV+GdGnoD2+KnJxf4fxMH//KsbsRofOzyVMn+74IbLNQlpd6SbrDz5ihddptdwk+cZImoL6r0KosaJD+Hik7hJCGsUZSD8fQVNy0vAnUnlje/G3AbPbOFbEh14gxsWbaDRW9lRoubMwQLPrMJjARQp0ERq58qVtCzUVLxDERw6sEF8TASKa8P/OtxQcyXJm969mj0gVwh5dJulnd1rtr/6QSBo3zizxlnDfmvAy/AbMjfOEcFjIRbGKDBeTmtkTHF832rC4AOV8Ob6cv3v6aDF98o5c8GnIoVNWx77sSRvZhP5WrXdtJsuIAy+zDyKkZCQmq3UqWcs2eUD8DYUWyoBgkuzI6kJHYKes71rUsJM0AvTgCS3C4DVKMCYtuQZ7yoSpN33Ycnxg5nDYotpPj8CqHB1GfHv72k2sae8THl0MibnngBftdMGV3g/dx50WyhBKMaEH4oFDOmI5nYn1IG97Uem6ESk/6FEpidlAN4pOWnrKjPHFH1xG7BDxHV2rfbxkw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
