travis:
  secure:
    BINSTAR_TOKEN: NkoJasVT7gaKZ3WjAbM/bUpOMW/GYF/5OIwn77R5fbFHzcT1dFMsB5AzLn1nW7ZH0Op4HqDAcYCiqPCeicXCPXolS3nsgXDpwJxSdAobn4J/r+oImSpQQI7UFhL5E2Os+iLtohPid1JWEar3aHk3xHRSEfMEuqa+UPRceX1O2aUNANNU9FMBH/FSWypfqBTQmXY8YsH8Ff3btHeULXYXoXQ8XTEqSBSBVkpEoCJunPzLz3Mn2zH0nPghY8E9J8AsWpj+s5J7LdAp9I/7VVquKG/RTVOpFJ6c8+28gd/CGn1NgXVJNLzDkR8yrZOE3OFfGzptyWHiN37nKWtrg/O0XoiK6ZC/GNDXpWUnUvHIoYiixbQ6gmFhmvfa0EORwcEvMsFeD0BM12noX3IE+Yburnzcn/VRtCcJ5A8LEUEKYtfGfO+8yVLlqN00x5wVwwi9uv1bYtgRROPQ/tzf3qQXs9cBMUVGC7fNURcled7+7inGPYU/bljUV15UJzyKIrPaLfc2ClrjZVvAdS0XR5Ld14+Yd7IR9q6JUJGY3EqJeyDQIBwPggoUrSiUZ/rzS6v+SK8nuT2wJLLhkj6aQABv1JpoFQf82gVthumSW1ndQS6kQgm2OKW9BwcKr6G9DfVQhpi3xy7EnHSBWqPrmyLukYr+FJD5HaojceuN909I8Hg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
